### ISSUE TITLE
[Feature] register the bundle as a Doctrine Migrations provider

### ISSUE THREAD

**Issue by dkarlovi** [netgen-layouts/layouts-core#23]
https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/

Basically, when you do `doctrine:migrations:status`, you can see bundles with their config auto-configured, then the migration config path is not required.

**Comment by emodric** [comment]
I'll take a look at it!

Thanks @dkarlovi :+1: !

**Comment by dkarlovi** [comment]
IIUC, you don't really need to do anything special expect having your bundle load a YAML config file (or via config extension / compiler pass, boils down to the same thing) which defines the path and namespace (same as in Twig).

Example:
https://github.com/pimcore/pimcore/blob/10.x/bundles/CoreBundle/Resources/config/pimcore/doctrine_migrations.yaml#L3-L4

**Comment by emodric** [comment]
Hm... Our migrations are not part of any bundle, so I doubt  notation similar to `@PimcoreCoreBundle/Migrations` will work. Is there any alternative, e.g. a path relative to project root?

**Comment by dkarlovi** [comment]
You could try

```yaml
doctrine_migrations:
    migrations_paths:
        'Netgen\Core\Migrations': '../../layouts-core/migrations' # assumes you're in vendor/netgen together
```

maybe? Not sure if it will work, but it might.
